### ISSUE TITLE
Adaugare comentarii pe cod conform std Java

### ISSUE THREAD

**Issue by TeoCristescu** [TeoCristescu/tema1_ip#31]
Va rog sa va adaugati comentarii pe cod conform standardului java pentru comentarii
V-am atasat mia jos un link.
http://particletree.com/features/successful-strategies-for-commenting-code/

**Comment by TeoCristescu** [comment]
Lasati aici comentariu cand ati terminat fiecare.

**Comment by lacramioara-git** [comment]
Am adaugat comentarii claselor FilterBySizeTask,SitemapTask si DirectoryNotFoundException, conform coding-style-ului Java.

**Comment by TeoCristescu** [comment]
> Lasati aici comentariu cand ati terminat fiecare.

**Comment by TeoCristescu** [comment]
Am adaugat comentarii claselor pe care le am implementat
